on:
  release:
    types:
      - published

name: Deploy Extension
jobs:
  build:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 20
    outputs:
      vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}
    steps:
      - name: Setup GIT for Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        if: runner.os == 'Windows'
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run compile
      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: stub
          dryRun: true
      - name: Upload Extension Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ steps.packageExtension.outputs.vsixPath }}

  publish:
    name: Publish Github Action
    needs:
      - build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Node v20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: |
            # Summary
            See [changelog](https://github.com/audiofab/fv1-vscode/blob/main/CHANGELOG.md#change-log) for details.
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: ${{ needs.build.outputs.vsixPath }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ needs.build.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com
